### ISSUE TITLE
Another invalid sequence at position error in A2lParser

### ISSUE THREAD

**Issue by digamma23** [Sauci/pya2l#17] opened 2019-05-15 04:32 UTC
File "\pya2l-0.0.1\pya2l\parser\grammar\parser.py", line 174, in p_error  raise A2lFormatException('invalid sequence at position ', p.lexpos, string=p.lexer.lexdata)

Here's the repeating part of the a2l file that I am using:
/begin CHARACTERISTIC SFB_R_FFO_DE.Properties._1_.Qly "" VALUE 36453 _UBYTE 0 NO_COMPU_METHOD 0 255
			/begin ANNOTATION
				/begin ANNOTATION_TEXT
                  "Factor 1.0"
                  "Offset 0"
				/end ANNOTATION_TEXT
				ANNOTATION_LABEL "CalInPatcher Additional Attributes"
			/end ANNOTATION
			SYMBOL_LINK "SFB_R_FFO_DE.Properties._1_.Qly" 0
		/end CHARACTERISTIC

**If I remove the line with SYMBOL_LINK, the error is gone.**

Could you explain how to debug this?

**Comment by Sauci** [comment] 2019-05-22 10:44
Sorry for the delayed answer. Do you know which version of the **A2L** format specification you use? Because depending on it, either ```SYMBOL_LINK``` is a new keyword introduced after the specification I used to write the grammar and lexer, or you have specified a custom ```CHARCTERISTIC``` node in the **A2ML** description. Please let me know which of those two cases you are facing to.

**Comment by vaasu070** [comment] 2020-10-21 13:19
I am also having same problem. What files need to be changed to in source code to include `SYMBOL_LINK`?

**Comment by Sauci** [comment] 2023-06-19 18:50
Hello @digamma23, @vaasu070, after a major update of the package, the parser does not crash on `SYMBOL_LINK` anymore. It is not part of the tree as I don't have the specification for it, but you get all other information. You can have a look at the test `test_issue_17` [here](https://github.com/Sauci/pya2l/blob/develop/pya2l/regression_test.py). I will close this issue now. So if you want to give it a try, please install the latest version of the package.

**Closed by Sauci** 2023-06-19 18:50 UTC

**Comment by Sauci** [comment] 2023-10-01 11:30
@digamma23 , @vaasu070 , the `SYMBOL_LINK` property is now properly handled (from version **0.1.1**).
